### ISSUE TITLE
Can't find dependent libraries

### ISSUE THREAD

**Issue by xmj233** [dynarithmic/twain_library-java#14]
Hello
I followed the steps in readme to put all the relevant files into the libs directory。
<img width="360" alt="image" src="https://github.com/user-attachments/assets/f421fdd0-d2ef-49d1-bce1-de13ca0ca66b">
and added VM options: -Djava.library.path=Z:\IdeaProjects\DigitalArchivesProcessor\libs.

But when I execute the test code,
<img width="480" alt="image" src="https://github.com/user-attachments/assets/afe7159b-a262-4eb4-8a81-73415798d3d0">
it reports an error
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/c9bc0e5a-77bf-4be3-a4d5-0c045eef03df">
This is my first time encountering these things, and I don't know if there is a problem with my operation. If you know this question, please help me.

**Comment by dynarithmic** [comment]
The resource files and DLL's must be in a directory available by your system path, not your java library path.

**Comment by Limxxx** [comment]
hello，I have placed the relevant files in D:\dtwain\dll, and also added VM options：-Djava.library.path=D:\dtwain\dll to the code. However, the same problem persists when running the code.
![image](https://github.com/user-attachments/assets/ad435376-a00d-481d-b4a4-56567495783c)
![image](https://github.com/user-attachments/assets/a6e73af0-8c7e-47a7-93d0-17b7ff680a0a)
