### ISSUE TITLE
Run new TwainSession(); Have a problem

### ISSUE THREAD

**Issue by Limruu** [dynarithmic/twain_library-java#16]
hello，According to the sample code to run, appear com. Dynarithmic. Twain. Exceptions. DTwainJavaAPIException: twain Session Could not start.The following image:
![image](https://github.com/user-attachments/assets/3278c6f2-4db2-4b55-8fa0-6d3eae3d2b9e)
If you know this problem, please help me

**Comment by dynarithmic** [comment]
There is an issue with your TWAIN setup.  Starting a TWAIN session should only fail if for some reason, TWAINDSM.DLL does not exist, cannot be found, cannot be opened, or corrupted in some way.

Note that you are running a 64-bit application, not 32-bit.  This means that TWAINDSM.DLL is the Twain Data Source manager that is loaded.  Do you have this file existing where it can be found and opened?

If you ran the DTWDEMO.exe program that exists in the [main DTWAIN repository](https://github.com/dynarithmic/twain_library/tree/master/binaries/64bit), does that work correctly?

**Comment by dynarithmic** [comment]
Closing issue as no feedback to the error has been provided.
